### ISSUE TITLE
href

### ISSUE THREAD

**Issue by martoio** [ericrutledge/f1-3-c2p1-colmar-academy#2]
If you want to point to nothing, make sure you put ``#`` as the ``href``. Otherwise, your ``<a>`` is technically an error.
https://github.com/ericrutledge/f1-3-c2p1-colmar-academy/blob/513685b3fdad1fe4481e9b2740c737dcb7e7e9d5/colmaracademy/index.html#L23

**Comment by ericrutledge** [comment]
Fair. I'll try to remember that. I imagine that I would always try to have something in there to make it work.
