### ISSUE TITLE
Class/ID names

### ISSUE THREAD

**Issue by martoio** [ericrutledge/f1-3-c2p1-colmar-academy#4]
Best practice tip: Use ``kebab-case-notation`` for your ID/class names in HTML and CSS. It makes things easier to read and it's an established industry practice.

https://github.com/ericrutledge/f1-3-c2p1-colmar-academy/blob/513685b3fdad1fe4481e9b2740c737dcb7e7e9d5/colmaracademy/index.html#L61

**Comment by ericrutledge** [comment]
Thank you
